/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csvteatudliitmine;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author margus-matis.roo
 */
public class CSVnullarvudeliitmine extends javax.swing.JFrame {

    /*  String filename = "Create-MyCSV.csv";

    private static List readFromFile(String filename) throws FileNotFoundException, IOException {
        List<Numbers> thisnumbers = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            br.readLine();
            for (String line; (line = br.readLine()) != null; ) {
                if (line.split(";")[11].isEmpty()) {
                    String[] numbers = line.split(";");
                    
                }
            }
            
            
            return null;
        }

    }
     */
    /**
     * Creates new form CSVTeatudliitminejalahutamine
     *
     * @throws java.io.FileNotFoundException
     */
    public CSVnullarvudeliitmine() throws FileNotFoundException {
        initComponents();

    }

    // public class JRadioButtonActionListener {
    //      ActionListener sliceActionListener = new ActionListener() {
    //          public void actionPerformed(ActionEvent actionEvent) {
    //               AbstractButton aButton = (AbstractButton) actionEvent.getSource();
    //               taResult(aButton.append());
    //           }
    //       };
    //       jRadioButton1.addActionListener(sliceActionListener);
    // }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btnButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Teatud Arvude Liitmine"), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));

        taResult.setEditable(false);
        taResult.setColumns(20);
        taResult.setRows(5);
        jScrollPane2.setViewportView(taResult);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Paarisarvud");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Paaritudarvud");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("5-lõppevad");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("0-lõppevad");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        btnButton1.setText("Nupp");
        btnButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addGap(0, 169, Short.MAX_VALUE))
            .addComponent(btnButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed

    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed

    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void btnButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton1ActionPerformed
        String csvFile = "Create-MyCSV.csv";
        File f = new File(csvFile);
        BufferedReader br = null;
        String line = "";
        String cvsSplitBy = ";";

        taResult.setText("");
        if (f.exists() && !f.isDirectory()) {
            taResult.setText("");

            try {

                br = new BufferedReader(new FileReader(csvFile));
                while ((line = br.readLine()) != null) {

                    String[] mass = line.split(cvsSplitBy);
                    String awn0 = mass[0].replaceAll("[^0-9.]", ""); //Tuleb ainult välja anda 'row'i milles on kõik 3 numbrid (n: 321), 
                    String awn1 = mass[1].replaceAll("[^0-9.]", ""); //kui on segu siis ei sobi (n: a42 või 5e2)
                    String awn2 = mass[2].replaceAll("[^0-9.]", "");
                    String awn3 = mass[3].replaceAll("[^0-9.]", "");
                    String awn4 = mass[4].replaceAll("[^0-9.]", "");
                    String awn5 = mass[5].replaceAll("[^0-9.]", "");
                    String awn6 = mass[6].replaceAll("[^0-9.]", "");
                    String awn7 = mass[7].replaceAll("[^0-9.]", "");
                    String awn8 = mass[8].replaceAll("[^0-9.]", "");
                    String awn9 = mass[9].replaceAll("[^0-9.]", "");
                    String awn10 = mass[10].replaceAll("[^0-9.]", "");
                    String awn11 = mass[11].replaceAll("[^0-9.]", "");

                   // try {
                   //     Integer.parseInt(awn0);
                   // } catch (NumberFormatException e) {
                   //     // Error
                   // }
                    
                    if (jRadioButton1.isSelected()) {
                        taResult.append(awn0 + " ; " + awn1 + " ; " + awn2 + " ; " + awn3 + " ; " + awn4 + " ; " + awn5 + " ; " + awn6
                                + " ; " + awn7 + " ; " + awn8 + " ; " + awn9 + " ; " + awn10 + " ; " + awn11 + "\n");

                    } else if (jRadioButton2.isSelected()) {
                        taResult.append(awn0 + " ; " + awn1 + " ; " + awn2 + " ; " + awn3 + " ; " + awn4 + " ; " + awn5 + " ; " + awn6
                                + " ; " + awn7 + " ; " + awn8 + " ; " + awn9 + " ; " + awn10 + " ; " + awn11 + "\n");

                    } else if (jRadioButton3.isSelected()) {
                        taResult.append(awn0 + " ; " + awn1 + " ; " + awn2 + " ; " + awn3 + " ; " + awn4 + " ; " + awn5 + " ; " + awn6
                                + " ; " + awn7 + " ; " + awn8 + " ; " + awn9 + " ; " + awn10 + " ; " + awn11 + "\n");

                    } else if (jRadioButton4.isSelected()) {
                        taResult.append(awn0 + " ; " + awn1 + " ; " + awn2 + " ; " + awn3 + " ; " + awn4 + " ; " + awn5 + " ; " + awn6
                                + " ; " + awn7 + " ; " + awn8 + " ; " + awn9 + " ; " + awn10 + " ; " + awn11 + "\n");

                    }
                }
            } catch (FileNotFoundException e) {
            } catch (IOException e) {
            } finally {
                if (br != null) {
                    try {
                        br.close();
                    } catch (IOException e) {
                    }
                }
            }

        } else {

            taResult.setText("Fail on puudu, ei saa midagi teha.");
        }
    }//GEN-LAST:event_btnButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSVnullarvudeliitmine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSVnullarvudeliitmine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSVnullarvudeliitmine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSVnullarvudeliitmine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CSVnullarvudeliitmine().setVisible(true);

                } catch (FileNotFoundException ex) {
                    Logger.getLogger(CSVnullarvudeliitmine.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnButton1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taResult;
    // End of variables declaration//GEN-END:variables
}
