/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csvteatudliitmine;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author margus-matis.roo
 */
public class CSVnullarvudeliitmine extends javax.swing.JFrame {

    List<String> fileContents = new ArrayList<>();

    String filename = "Create-MyCSV.csv";

    private List readFromFile(String filename) throws FileNotFoundException, IOException {
        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            br.readLine();
            for (String line; (line = br.readLine()) != null;) {
                fileContents.add(line);
                taResult.append(line + "\n");
            }
            return null;
        }

    }

    /**
     * Creates new form CSVTeatudliitminejalahutamine
     *
     * @throws java.io.FileNotFoundException
     */
    public CSVnullarvudeliitmine() throws FileNotFoundException {
        initComponents();

    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btnButton1 = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFinalResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Teatud Arvude Liitmine"), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));

        taResult.setEditable(false);
        taResult.setColumns(20);
        taResult.setRows(5);
        jScrollPane2.setViewportView(taResult);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Paarisarvud");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Paaritudarvud");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("5-lõppevad");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("0-lõppevad");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        btnButton1.setText("Näita");
        btnButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton1ActionPerformed(evt);
            }
        });

        btnShow.setText("Filtreeri");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        taFinalResult.setEditable(false);
        taFinalResult.setColumns(20);
        taFinalResult.setRows(5);
        jScrollPane1.setViewportView(taFinalResult);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(btnButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnShow)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(btnShow))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed

    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed

    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void btnButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton1ActionPerformed
        String csvFile = "Create-MyCSV.csv";
        File f = new File(csvFile);

        taResult.setText("");
        if (f.exists() && !f.isDirectory()) {
            taResult.setText("");
            try {
                readFromFile(csvFile);

            } catch (IOException ex) {
                Logger.getLogger(CSVnullarvudeliitmine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnButton1ActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        taResult.setText("");
        taFinalResult.setText("");
        if (jRadioButton1.isSelected()) {
            int sum = 0;
            int count = 0;
            for (int i = 0; i < fileContents.size(); i++) {
                String[] parts = fileContents.get(i).split(";");
                for (int j = 0; j < parts.length; j++) {
                    if (isNumeric(parts[j])) {
                        int s = Integer.parseInt(parts[j]);
                        if ((s % 2) == 0) {
                            taResult.append(parts[j] + " ");
                            sum += s;
                            count += 1;
                        }
                    }
                    if (j == parts.length - 1) {
                        taResult.append("\n");
                    }
                }

            }

            taFinalResult.append("Paaris arvude lõpptulemus -> " + sum + "\n");
            taFinalResult.append("Palju paaris numbrid on olemas -> " + count + "\n");

            /*
            System.out.println("Paaris arvude lõpptulemus -> " + sum);
            System.out.println("Palju paaris numbrid on olemas -> " + count);
            System.out.println("");
             */
        } else if (jRadioButton2.isSelected()) {
            int sum1 = 0;
            int count1 = 0;
            for (int i = 0; i < fileContents.size(); i++) {
                String[] parts1 = fileContents.get(i).split(";");
                for (int j = 0; j < parts1.length; j++) {
                    if (isNumeric(parts1[j])) {
                        int s1 = Integer.parseInt(parts1[j]);
                        if ((s1 % 6) == 3) {
                            taResult.append(parts1[j] + " ");
                            sum1 += s1;
                            count1 += 1;
                        }
                    }
                    if (j == parts1.length - 1) {
                        taResult.append("\n");
                    }
                }
            }
            taFinalResult.append("Paaritu arvude lõpptulemus -> " + sum1 + "\n");
            taFinalResult.append("Palju paaritu numbrid on olemas -> " + count1 + "\n");

        } else if (jRadioButton3.isSelected()) {
            int sum2 = 0;
            int count2 = 0;
            for (int i = 0; i < fileContents.size(); i++) {
                String[] parts2 = fileContents.get(i).split(";");
                for (int j = 0; j < parts2.length; j++) {
                    if (isNumeric(parts2[j])) {
                        int s2 = Integer.parseInt(parts2[j]);
                        if ((s2 % 10) == 5) {
                            taResult.append(parts2[j] + " ");
                            sum2 += s2;
                            count2 += 1;
                        }
                    }
                    if (j == parts2.length - 1) {
                        taResult.append("\n");
                    }
                }
            }
            taFinalResult.append("5-lõppevade arvude lõpptulemus -> " + sum2 + "\n");
            taFinalResult.append("Palju 5-lõppevad numbrid on olemas -> " + count2 + "\n");

        } else if (jRadioButton4.isSelected()) {
            int sum3 = 0;
            int count3 = 0;
            for (int i = 0; i < fileContents.size(); i++) {
                String[] parts3 = fileContents.get(i).split(";");
                for (int j = 0; j < parts3.length; j++) {
                    if (isNumeric(parts3[j])) {
                        int s3 = Integer.parseInt(parts3[j]);
                        if ((s3 % 10) == 0) {
                            taResult.append(parts3[j] + " ");
                            sum3 += s3;
                            count3 += 1;
                        }
                    }
                    if (j == parts3.length - 1) {
                        taResult.append("\n");
                    }
                }
            }
            taFinalResult.append("0-lõppevade arvude lõpptulemus -> " + sum3 + "\n");
            taFinalResult.append("Palju 0-lõppevad numbrid on olemas -> " + count3 + "\n");

        }
    }//GEN-LAST:event_btnShowActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSVnullarvudeliitmine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSVnullarvudeliitmine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSVnullarvudeliitmine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSVnullarvudeliitmine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new CSVnullarvudeliitmine().setVisible(true);

                } catch (FileNotFoundException ex) {
                    Logger.getLogger(CSVnullarvudeliitmine.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private boolean isNumeric(String strNum) {
        try {
            int d = Integer.parseInt(strNum);
        } catch (NumberFormatException | NullPointerException nfe) {
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnButton1;
    private javax.swing.JButton btnShow;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taFinalResult;
    private javax.swing.JTextArea taResult;
    // End of variables declaration//GEN-END:variables
}
